image: gitpod/workspace-full  # Imagen universal con herramientas preinstaladas
ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - name: Inicializar Entorno
    init: |
      echo "Instalando dependencias generales..."
      sudo apt-get update
      # Aquí añades herramientas necesarias (ej: n8n, CLI de Supabase)
