image: flutter  # O la imagen que uses (ej: node)
tasks:
  - name: Run Flutter App
    init: |
      flutter pub get
      echo "SUPABASE_URL=$SUPABASE_URL" > .env
      echo "SUPABASE_KEY=$SUPABASE_KEY" >> .env
    command: flutter run -d chrome
ports:
  - port: 3000
    onOpen: open-preview
